/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-error": "#ffffff",
          "on-background": "#191c1e",
          "on-secondary-fixed": "#1a1c1c",
          "on-tertiary-fixed-variant": "#3f465c",
          "on-secondary-fixed-variant": "#454747",
          "on-primary": "#ffffff",
          "on-tertiary-container": "#f8f7ff",
          "tertiary-fixed-dim": "#bec6e0",
          "on-secondary": "#ffffff",
          "error": "#ba1a1a",
          "on-surface-variant": "#5c403c",
          "surface-container-lowest": "#ffffff",
          "surface-container-low": "#f2f4f6",
          "on-tertiary": "#ffffff",
          "surface-bright": "#f7f9fb",
          "inverse-primary": "#ffb4ab",
          "on-primary-fixed-variant": "#93000b",
          "surface-container-high": "#e6e8ea",
          "on-secondary-container": "#616363",
          "surface": "#f7f9fb",
          "secondary-container": "#dfe0e0",
          "tertiary": "#51596f",
          "primary": "#b70011",
          "inverse-surface": "#2d3133",
          "surface-container": "#eceef0",
          "primary-fixed-dim": "#ffb4ab",
          "background": "#f7f9fb",
          "primary-fixed": "#ffdad6",
          "on-surface": "#191c1e",
          "on-primary-container": "#fff6f5",
          "surface-tint": "#bf0715",
          "tertiary-container": "#6a7188",
          "primary-container": "#dc2626",
          "on-error-container": "#93000a",
          "secondary": "#5d5f5f",
          "on-primary-fixed": "#410002",
          "outline": "#916f6b",
          "surface-dim": "#d8dadc",
          "on-tertiary-fixed": "#131b2e",
          "outline-variant": "#e6bdb8",
          "error-container": "#ffdad6",
          "surface-container-highest": "#e0e3e5",
          "secondary-fixed": "#e2e2e2",
          "inverse-on-surface": "#eff1f3",
          "surface-variant": "#e0e3e5",
          "tertiary-fixed": "#dae2fd",
          "secondary-fixed-dim": "#c6c6c7"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "container-padding": "24px",
          "xl": "40px",
          "gutter": "16px",
          "sm": "8px",
          "lg": "24px",
          "md": "16px",
          "xs": "4px",
          "unit": "4px"
      },
      "fontFamily": {
          "headline-lg": ["Inter"],
          "body-md": ["Inter"],
          "utility-sm": ["Lexend"],
          "display-xl": ["Inter"],
          "body-lg": ["Inter"],
          "headline-md": ["Inter"],
          "label-red": ["Lexend"]
      },
      "fontSize": {
          "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
          "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "utility-sm": ["12px", {"lineHeight": "1", "fontWeight": "700"}],
          "display-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
          "body-lg": ["18px", {"lineHeight": "1.5", "fontWeight": "500"}],
          "headline-md": ["24px", {"lineHeight": "1.2", "fontWeight": "700"}],
          "label-red": ["14px", {"lineHeight": "1", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
